# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 21:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('audio_base', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_translation', models.CharField(max_length=750)),
                ('foreign_translation', models.CharField(max_length=750)),
                ('audio_id', models.CharField(max_length=250)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Language')),
            ],
        ),
        migrations.CreateModel(
            name='PhraseStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_make_streak', models.BooleanField(default=False)),
                ('streak_number', models.IntegerField(default=0)),
                ('last_heard', models.DateTimeField(default=datetime.datetime(2017, 1, 11, 15, 28, 11, 464027))),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Phrase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
